version: 2

sources:
  - name: taxi_trips
    description: "Raw source tables stored in BigQuery."
    database: de-zoomcamp-489309
    schema: zoomcamp
    tables:
      - name: yellow_tripdata
        description: "Yellow taxi trips source table."
      - name: green_tripdata
        description: "Green taxi trips source table."
